### ISSUE TITLE
Dockerfile: Build fails during Pillow installation

### ISSUE THREAD

**Issue by zeta0134** [zeta0134/pikmin-nds#32]
When building the dockerfile, Pillow installation fails with the following tracelog:

```
Step 5/17 : RUN pip3 install Pillow
 ---> Running in d6e10ca7f206
Downloading/unpacking Pillow
  Running setup.py (path:/tmp/pip-build-2nco6acw/Pillow/setup.py) egg_info for package Pillow
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-2nco6acw/Pillow/setup.py", line 892, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW),
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "<string>", line 15, in replacement_run
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 193, in find_sources
        mm.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 277, in run
        self.add_defaults()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 306, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 183, in add_defaults
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/lib/python3.4/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-build-2nco6acw/Pillow/setup.py", line 332, in finalize_options
        if not self.parallel:
      File "/usr/lib/python3.4/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: parallel
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info/Pillow.egg-info

writing top-level names to pip-egg-info/Pillow.egg-info/top_level.txt

writing pip-egg-info/Pillow.egg-info/PKG-INFO

writing dependency_links to pip-egg-info/Pillow.egg-info/dependency_links.txt

writing manifest file 'pip-egg-info/Pillow.egg-info/SOURCES.txt'

/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'

  warnings.warn(msg)

/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'project_urls'

  warnings.warn(msg)

warning: manifest_maker: standard file '-c' not found



Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-2nco6acw/Pillow/setup.py", line 892, in <module>

    zip_safe=not (debug_build() or PLATFORM_MINGW),

  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "<string>", line 15, in replacement_run

  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 193, in find_sources

    mm.run()

  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 277, in run

    self.add_defaults()

  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 306, in add_defaults

    sdist.add_defaults(self)

  File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 183, in add_defaults

    build_ext = self.get_finalized_command('build_ext')

  File "/usr/lib/python3.4/distutils/cmd.py", line 299, in get_finalized_command

    cmd_obj.ensure_finalized()

  File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized

    self.finalize_options()

  File "/tmp/pip-build-2nco6acw/Pillow/setup.py", line 332, in finalize_options

    if not self.parallel:

  File "/usr/lib/python3.4/distutils/cmd.py", line 103, in __getattr__

    raise AttributeError(attr)

AttributeError: parallel

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-2nco6acw/Pillow
```

**Comment by zeta0134** [comment]
Closed by #34
